openapi: 3.0.3
info:
  title: Sample API Service
  description: Service for sample api
  version: "1.0"
servers:
- url: http://localhost:8002
paths:
  /openapi.json:
    get:
      tags:
      - sampleApi
      summary: Download ./gen/http/openapi.json
      operationId: sampleApi#/openapi.json
      responses:
        "200":
          description: File downloaded
  /users/{id}:
    get:
      tags:
      - sampleApi
      summary: show sampleApi
      operationId: sampleApi#show
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        schema:
          type: integer
          description: ID
          example: 6846785480018905122
          format: int64
        example: 1155400276225794180
      responses:
        "200":
          description: OK response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                email: Molestiae unde.
                id: 6689576278252517781
                name: Aliquam quam enim blanditiis cupiditate exercitationem.
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: Email
          example: Et omnis.
        id:
          type: integer
          description: ID
          example: 5778282642062992305
          format: int64
        name:
          type: string
          description: Name
          example: Sed et quam sit aut fuga error.
      example:
        email: Corporis consequatur odio voluptate.
        id: 6190762639104875073
        name: Et amet autem explicabo eligendi consequatur atque.
tags:
- name: sampleApi
  description: Sample API Service
