swagger: "2.0"
info:
  title: Greeting Service
  description: Service that manage greeting
  version: ""
host: localhost:8001
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /hello/{name}:
    get:
      tags:
      - greet
      summary: hello greet
      operationId: greet#hello
      parameters:
      - name: name
        in: path
        description: Name
        required: true
        type: string
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
